# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 권은지 포트폴리오
description: 반도체 장비 소프트웨어 전공자 권은지입니다. C/C++, C#, Python을 활용한 시스템 제어 및 소프트웨어 개발 역량을 갖추고 있습니다.
baseurl: "" # the subpath of your site, e.g. /support
url: https://eunji021.github.io # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: Portfolio #Define whether this is a knowledge base, help center, or something else
use_authors: true #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: 권은지 포트폴리오
header: My Projects
subheader: 반도체 장비 소프트웨어 전공자 권은지입니다. C/C++, C#, Python을 활용한 시스템 제어 및 소프트웨어 개발 역량을 갖추고 있습니다.

meta_image: odin-meta.png

# Social Links
twitter_username: 
facebook_page:
github_username: eunji021
email: gwun012@naver.com
linkedin_page:
instagram_username: 


# Navivation
nav_item_one: Github
nav_item_one_link: https://github.com/eunji021

nav_item_two: Email
nav_item_two_link: mailto:gwun012@naver.com

nav_item_three: #
nav_item_three_link: #

nav_button: Return to Home
nav_button_link: https://eunji021.github.io/

# More Help
help_one_title: GitHub
help_one_content: 제 깃허브를 방문해서 더 많은 프로젝트를 확인해 보세요.
help_one_button: Github
help_one_link: https://github.com/eunji021

help_two_title: Email
help_two_content: 프로젝트 및 채용 관련 문의는 이메일로 연락 부탁드립니다.
help_two_button: Email
help_two_link: mailto:gwun012@naver.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
